namespace Domain.Entities;

public sealed class Employee
{
    public int EmployeeId { get; set; }
    public string? LastName { get; set; }
    public string? FirstName { get; set; }
    public object? MiddleName { get; set; }
    public string? Gender { get; set; }
    public string? JobTitle { get; set; }
    public object EmployeeType { get; set; }
    public int Department { get; set; }
    public object? Branch { get; set; }
    public string? WorkStreet { get; set; }
    public string? WorkBlock { get; set; }
    public string? WorkZipCode { get; set; }
    public string? WorkCity { get; set; }
    public string? WorkCounty { get; set; }
    public string? WorkCountryCode { get; set; }
    public string? WorkStateCode { get; set; }
    public int Manager { get; set; }
    public object? ApplicationUserID { get; set; }
    public object? SalesPersonCode { get; set; }
    public object? OfficePhone { get; set; }
    public string? OfficeExtension { get; set; }
    public string? MobilePhone { get; set; }
    public string? Pager { get; set; }
    public object? HomePhone { get; set; }
    public object? Fax { get; set; }
    public string? eMail { get; set; }
    public DateTime StartDate { get; set; }
    public object? StatusCode { get; set; }
    public double Salary { get; set; }
    public string? SalaryUnit { get; set; }
    public double EmployeeCosts { get; set; }
    public string? EmployeeCostUnit { get; set; }
    public object? TerminationDate { get; set; }
    public object? TreminationReason { get; set; }
    public string? BankCode { get; set; }
    public object? BankBranch { get; set; }
    public object? BankBranchNum { get; set; }
    public object? BankAccount { get; set; }
    public string? HomeStreet { get; set; }
    public string? HomeBlock { get; set; }
    public string? HomeZipCode { get; set; }
    public string? HomeCity { get; set; }
    public string? HomeCounty { get; set; }
    public string? HomeCountry { get; set; }
    public string? HomeState { get; set; }
    public DateTime DateOfBirth { get; set; }
    public string? CountryOfBirth { get; set; }
    public string? MartialStatus { get; set; }
    public object? NumOfChildren { get; set; }
    public string? IdNumber { get; set; }
    public object? CitizenshipCountryCode { get; set; }
    public object? PassportNumber { get; set; }
    public object? PassportExpirationDate { get; set; }
    public object? Picture { get; set; }
    public object? Remarks { get; set; }
    public string? SalaryCurrency { get; set; }
    public string? EmployeeCostsCurrency { get; set; }
    public object? WorkBuildingFloorRoom { get; set; }
    public object? HomeBuildingFloorRoom { get; set; }
    public object? Position { get; set; }
    public object? AttachmentEntry { get; set; }
    public object? CostCenterCode { get; set; }
    public object? CompanyNumber { get; set; }
    public object? VacationPreviousYear { get; set; }
    public object? VacationCurrentYear { get; set; }
    public object? MunicipalityKey { get; set; }
    public string? TaxClass { get; set; }
    public string? IncomeTaxLiability { get; set; }
    public string? Religion { get; set; }
    public string? PartnerReligion { get; set; }
    public double? ExemptionAmount { get; set; }
    public string? ExemptionUnit { get; set; }
    public string? ExemptionCurrency { get; set; }
    public double? AdditionalAmount { get; set; }
    public string? AdditionalUnit { get; set; }
    public string? AdditionalCurrency { get; set; }
    public object? TaxOfficeName { get; set; }
    public object? TaxOfficeNumber { get; set; }
    public object? HealthInsuranceName { get; set; }
    public object? HealthInsuranceCode { get; set; }
    public string? HealthInsuranceType { get; set; }
    public object? SocialInsuranceNumber { get; set; }
    public string? ProfessionStatus { get; set; }
    public string? EducationStatus { get; set; }
    public string? PersonGroup { get; set; }
    public object? JobTitleCode { get; set; }
    public object? BankCodeForDATEV { get; set; }
    public string? DeviatingBankAccountOwner { get; set; }
    public object? SpouseFirstName { get; set; }
    public object? SpouseSurname { get; set; }
    public object? ExternalEmployeeNumber { get; set; }
    public object? BirthPlace { get; set; }
    public string? PaymentMethod { get; set; }
    public object? STDCode { get; set; }
    public string? CPF { get; set; }
    public object? CRCNumber { get; set; }
    public string? AccountantResponsible { get; set; }
    public string? LegalRepresentative { get; set; }
    public string? DIRFResponsible { get; set; }
    public object? CRCState { get; set; }
    public string? Active { get; set; }
    public object? IDType { get; set; }
    public int BPLID { get; set; }
    public object? PassportIssueDate { get; set; }
    public object? PassportIssuer { get; set; }
    public string? QualificationCode { get; set; }
    public string? PRWebAccess { get; set; }
    public string? PreviousPRWebAccess { get; set; }
    public string? WorkStreetNumber { get; set; }
    public string? HomeStreetNumber { get; set; }
    public object? LinkedVendor { get; set; }
    public DateTime CreateDate { get; set; }
    public string? CreateTime { get; set; }
    public DateTime UpdateDate { get; set; }
    public string? UpdateTime { get; set; }
    public string? EmployeeCode { get; set; }
    public string? ARetSEFAZ { get; set; }
    public string? U_TipoUsuario { get; set; }
    public string? U_TipoAcesso { get; set; }
    public string? U_UsuarioIntegracao { get; set; }
    public string? U_AdmFibra { get; set; }
    public List<object> EmployeeAbsenceInfoLines { get; set; } = [];
    public List<object> EmployeeEducationInfoLines { get; set; } = [];
    public List<object> EmployeeReviewsInfoLines { get; set; } = [];
    public List<object> EmployeePreviousEmpoymentInfoLines { get; set; } = [];
    public List<object> EmployeeRolesInfoLines { get; set; } = [];
    public List<object> EmployeeSavingsPaymentInfoLines { get; set; } = [];
    public List<object> EmployeeBranchAssignment { get; set; } = [];
}